### ISSUE TITLE
Breakout isn't working on v1033

### ISSUE THREAD

**Issue by riven60** [JakBaranowski/ground-branch-game-modes#32]
**Describe the bug**
when I run on GB v1033 I hear the enemies and see a black square with a yellow crosshair inside where they should be. They yell at me and follow me around but never shoot
**To Reproduce**
1. Go to 'Ground Branch'
2. Click on 'Breakout Game Mode'
3. Scroll down to 'choose any map and run around'

**Expected behavior**
![breakout_bug](https://user-images.githubusercontent.com/17430846/230802413-898a5083-1ba6-4e11-81c4-2d99b467ac12.jpg)

**Screenshots**
![image](https://user-images.githubusercontent.com/17430846/230802376-73c125d0-0a20-46ac-a9df-db70d5241b2a.png)

**Desktop (please complete the following information):**
 - Game version: V 1033

**Comment by nPHYN1T3** [comment]
Not sure this is considered a "bug" since the newest release says it's only for 1032. I've been waiting for this to be updated for 1033.

**Comment by riven60** [comment]
My bad, I didn't know how to report it as I was looking forward to playing
breakout mode and had just heard about it, I didn't know it was only for
v1032.

I'm sorry about that. I hope you continue your work it looks like so
much fun.

**Comment by nPHYN1T3** [comment]
Bug or not perhaps this may spur an update. I kinda figured the project was dead which sucks because I much prefer these game modes.

**Comment by riven60** [comment]
I don't think they are dead. I imagine the v1033 update just disabled a lot
of them and the player base is still relatively small to begin with. The
guys I play are always on "home" hosted servers and though we are just
around 6 in numbers we are hoping to add more to that and with your awesome
looking game modes, that should be an easy process. We enjoy ground Branch
for the teamwork involved(most of my friends are ex-military) and your game
modes promotes teamwork more than the Blackfoot studios Intel retrieval or
insurgent hunt(or w.e it's called)

**Comment by nPHYN1T3** [comment]
Not -My- game modes, this isn't my project, other wise I'd have updated it ;)

**Comment by riven60** [comment]
Oh, haha I'm replying via email and I just realized that you are another
fan/user of these mods. I hope Jake baranowski updates his mods for v1033!

**Comment by nPHYN1T3** [comment]
Well like I said I kinda suspect this is dead. Author hasn't weighed in but when I saw there was no movement once 1033 was able to be opted into I kinda thought that was the end. I've developed similar stuff in the past the the changes to the game nuked all my work with no clear way forward to update so I suspect something similar has happened.

**Comment by riven60** [comment]
Well shit that's a shame. Sorry about your work being nuked as well.

**Comment by nPHYN1T3** [comment]
Tis how it goes...that said I also don't know why these game modes haven't just been pulled into the official game. Seems like with all the big stuff they are breaking it would be easiest for them to maintain some simple lua game modes themselves.

**Comment by riven60** [comment]
Yeah I agree. Seems like it would be simple enough to keep these game modes
along with the native game modes(which no-one plays lol)

**Comment by nPHYN1T3** [comment]
...it's all we play...now. :( I regret allowing the game to update on that note but that extends far past losing these game modes.

**Comment by riven60** [comment]
All we ever play is Intel retrieval :/

It's fun for a while just starts feeling stale after so many run throughs.

**Comment by nPHYN1T3** [comment]
Agreed, but what bothers me about Intel missions is the "bad intel." I've reported it, shown videos and screenshots of it but often times the Intel isn't where it's marked for me. Sadly I play more Tarkov just because GB gets stale quickly, the Ai is horrible (too easy or straight cheating) and the game is still very clunky. Slow and clunky feels punishing for the sake of punishing the player. I don't want COD inhuman ADHD style play but GB has a long way to go towards fluid and realistic feeling actions...nevermind *every* freaking game still uses capsule solliders for movement which creates that fake/inhuman center axis rotation that cheats you out of clean shots. I could rant all day but EA is EA...in ten years *IF* it's finished maybe it won't suck heh.

**Comment by riven60** [comment]
Yeah theyve done good work on the AI in the v1033 update and considering
the team is only like 8 guys, it's impressive what they've accomplished.
I've given up on tarkov unfortunately (I was an alpha player since 2017).
I'm moving on to ghosts of tabor on VR believe it or not. It's everything
you want in tarkov but VR it's A LOT of fun.

**Comment by nPHYN1T3** [comment]
They licensed an Ai engine for 1033. Never heard of Ghosts of Tabor. Checked the trailer but it was a kinda crappy montage that makes it look like that Ready or Not game. I play Tarkov offline (AKI) and still on an older build for technical reasons. It's not perfect but it's better than anything else I've tried.

**Comment by riven60** [comment]
Yeah too many cheaters online in tarkov. I might switch to the offline
version bc I don't even play it anymore (3500hours in-game tarkov)

Ghosts of Tabor is EFT but VR. It's very buggy bc it's in alpha still but
omg it's so much fun, even solo and with only 2 maps available. They have
more maps(videos and screenshots of them) but they are focusing on the bugs
first.

And what's even best about ghosts of tabor is the amount of developer
communication with the community. They have a dev-board so you know what
they are working on (unlike EFT, Nikita had to keep everything secret)

Fantastic game for what it is and will be. A LOT of EFT players are moving
to GoT.

I'd recommend watching a few YouTubers who make GoT content.  It can be a
very enjoyable experience.

**Comment by nPHYN1T3** [comment]
Cheaters are the least of my problems. Server outtages, special accounts (I've had my Blizzard account locked years ago repeatedly for the "suspicious activity" of loging in twice in a day), a-hole admins, incomparable mods, game/servers taken offline because the company wasn't making as much money as they wanted, Anti-Cheat / Anti-Piracy software that just makes a game garbage and punishes paying customers. I've refused Anti-Cheat since the Punk-Buster days. It's as stupid as Anti-Virus, cheat makers always find a way around the idiotic crap, in the mean time everyone else suffers invasive kernel rootkits and huge FPS drops to still end up facing cheaters...This is why I don't play anything online in general anymore. I bought GB to play offline but the 1033 build has just been a nightmare. I like *most* the new level changes (they killed Creek) but the game now looks like dogChit, soo many gear bugs, audio problems...just a horrible update. I hope 1034 will be better but that's like a year+ away.

**Comment by riven60** [comment]
i've been impressed by the v1033 update, the AI changes are fantastic,
night-raids are possible now, the GPNVG WP/Green look incredible. If you
ever want to play with me and my buddies, we generally start playing around
5-6pm EST.

my steam friend code is: 18977579   - if you'd like to add me as a friend
we can come up with some neat games to play with the 6-8 of us that we
would have.

**Comment by JakBaranowski** [comment]
Hi @riven60, thanks for the issue report. 

Development has been moved to the [forked repository](https://github.com/gbgmc/ground-branch-game-modes), since it was more up to date, and to make it easier for me and @Bob-AT to colaborate on the project. AFAIK the version of the project available there does work with Ground Branch v1033. If you can please download game modes from the forked project, installation guide is in the repo readme, and if the issues persist do spawn an issue report in that project.

That being said, the development is pretty slow since we're busy with other stuff. But if you, or @nPHYN1T3 are willing to help with the development feel free to fork the project and post Pull Requests. We'll try our best to address all PRs posted for the project.

**Comment by riven60** [comment]
Thanks SOO much JakBaranowski and Bob-AT!!!!!!


Sincerely,
Mark Chudoba

**Comment by ghost** [comment]
Indeed, glad to see this repo is dead but the project isn't. Hmm...release is actually on Nexusmods...well so much for that.

@riven60 Thanks for the invite but you'd probably not want me on the team. I've been playing solo so long I'd probably just be reckless due to having to play nuts since I have no one to watch my back or cover angles.

Helping would be up in the air as I'm reevaluating my projects and energy but the fact this is on Nexus gives me pause.

**Comment by riven60** [comment]
What kind of developer are you? Python, c, c#,c++,ruby, perl, JS?

**Comment by riven60** [comment]
I'm in cybersec myself, I'm learning Python and c++ to help further my
knowledge and career.

**Comment by ghost** [comment]
Jack of all master of none. Originally Basic (started in the 1980's heh) then C. I got fed up porting because every damned OS key functions would be behind different headers. Back in the day my "workstation" was 4 machines comprised of Linux, BSD, BeOS, Windows. I eventually moved to basically web programming since it was more universal. Google killed that and I kinda moved back to C / Rust but yes I do php, js, py, perl. I've written C#, lua (what Ground Branch is using)  and other things but unless you're getting super technical and large scale most the time the crap is all the same.

**Comment by riven60** [comment]
Why don't you get into GIS dev? There is a large demand for GIS devs

**Comment by ghost** [comment]
Lol I don't give a FEEEERK what's in demand I'm reeeeeTIRED! I just maintain my network/systems and write things I use. I had been prepping to knock off a few bucket list items [:read] my games that I had planned on doing since I was a kid but various developments have made me shelve that. At this point I'm fed up and burnt out as everything is EA and you make stuff and the devs kill it, you make stuff and the devs kill it...cue my earlier joke about that being development in general these days. Everything is too large to do from scratch which means you have to adopt frameworks and EZ bs that is either a malware vector or something that likes to yank the carpet out from under your work.

**Comment by riven60** [comment]
Lol I get it, you're burnt out. Take a well deserved break my friend. I'm
sure you've earned it.

**Comment by ghost** [comment]
Heh well the workaholic in me says I haven't earned Chit but that constant shifting BS really wears on you. Oh hey you build all this based on these API's...well we're retiring those but not replacing or updating them with something else. Sadly stuff like that and projects and things requiring you to be part of all these "cool kid clubs" has me locked out of most things these days so as I'm fenced out it's an unwanted and natural wind down. This project is a sad example, this evening you'll be playing the game modes while I'm locked out because they have the current releases locked behind a cool kid club (Nexus).

**Comment by riven60** [comment]
Nexus modding hub is a phase, I've seen plenty come and go.

**Comment by ghost** [comment]
That may be but it's yet another obnoxious signup wall. Like when things are released only on Discord...ug. More and more things behind signup walls that forbid people based on arbitrary rules. Geolocation, cell numbers, email domains. Anyhow I'll sub to the fork, perhaps one day it will be available to download again. Lol I suppose I could make a ticket about it heh.

**Comment by riven60** [comment]
Oh the world is going to hell in a hand basket for sure. These things like
Nexus, discord, reddit, Facebook or whatever the new shit is, proves it.
Generation born today won't know how to do anything but communicate using
screens.

**Comment by ghost** [comment]
Yulp. Funny thing, wAy back my Dad used to rib me about BeOS users being a cult and how I was glued to my systems. We're going out today and I'll sit there while he plays with his damn phone. I refuse to own a cellphone. I smashed my business cell years ago and never looked back. Meanwhile the whole planet is Pavlovs Dog for a ring, ding or whatever sound their cool kid app makes these days.

I hate the fact I have anything on Steam too. If I knew what Steam would have become I'd have never installed CS 1.6. We're not buying games, we're leasing half baked concepts that typically never get finished and will be dumped the second a profit margin or hype meter under performs heh.

...I almost forgot * SHAKES CANE ANGRILY! *

**Comment by riven60** [comment]
I miss cs1.5

**Comment by ghost** [comment]
LOL can this thread get anymore off the rails...ALIENS! Yay man and CS 1.6 screwed me. That was the first Steam release and I had JUST got a 32Mb GPU to run CS half decent...CS 1.6 was released and they added shadows and other crap with no option to disable them and my OK performance with my new GPU went back to crap. It was a real middle finger.

**Comment by riven60** [comment]
I had similar hardware lol just gotten a new PCI gpu(my motherboard didn't
support AGP). And it ran 1.3-1.5 great but it didn't run 1.6 worth shit.
And I had a nice sound card and everything.... The old days

**Comment by ghost** [comment]
Back then your computer was beige and you'd like it GD't! heh I remember when a Hercules monochrome video adapter was like WHOA heh. Glorious Green OR Amber.

**Comment by riven60** [comment]
Lol I don't even remember the brand of my GPU. Probably some shitty ATI PCI
card as AGP was the only other alternative

**Comment by JakBaranowski** [comment]
Hey @nPHYN1T3 , I'll try to post a release of the latest version on the forked project GH this week.

I'm not a huge fan of what you call sign-up walls either. We focused on Nexus since we've noticed Ground Branch mods on Nexus had thousands of downloads while this one had less than hundred.

Until then you can grab the source code from the tags page - https://github.com/gbgmc/ground-branch-game-modes/releases/tag/v1033.0.1 - our releases are nothing more than the source code with some project specific files filtered out.

**Comment by Bob-AT** [comment]
Just saw this ticket.

On the NexusMods page there was a mirror link for people that don't want to create a NexusMods
account. It was a mediafire.com folder  (for historical reasons.).

I've now used GitHub's release feature and uploaded the ZIPs 
at <https://github.com/gbgmc/ground-branch-game-modes/releases>.

**Comment by JakBaranowski** [comment]
@Bob-AT thanks for taking care of this.

@nPHYN1T3 you can grab the releases straight from the forked project GH page now.
